name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest tests

    - name: Build Docker image
      run: docker build -t fraud-app:latest .

    # (Optional) Run tests inside Docker
    - name: Test inside Docker
      run: |
        docker run --rm fraud-app:latest pytest tests
