services:
  api:
    build:
      context: .
      dockerfile: model_api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - ./fraud.db:/app/fraud.db
      - ./results:/app/results
      - ./models:/app/models
      - ./.streamlit:/root/.streamlit

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fraud
    ports:
      - "5432:5432"
